configDependencies:
  pacquet: ^0.11.12

enableGlobalVirtualStore: true

minimumReleaseAgeExclude:
  - "@oxfmt/*"
  - "@oxlint/*"
  - "@oxlint-tsgolint/*"
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - tsdown

trustPolicy: no-downgrade
